In [46]:
'''
steps
1. import cleaned tweets
2. import banks, merchents, mobile payments
3. stats: how many have both banks, merchant, mobile payments
4. divide the data into 3 categories -- tweets with at least two different entity types (banks&merchants, banks&mb, mb&merchants)
5. sample 100 from each category
'''

'\nsteps\n1. import cleaned tweets\n2. import banks, merchents, mobile payments\n3. stats: how many have both banks, merchant, mobile payments\n4. divide the data into 3 categories -- tweets with at least two different entity types (banks&merchants, banks&mb, mb&merchants)\n5. sample 100 from each category\n'

In [47]:
#step 1
%matplotlib inline 

import pandas as pd
from collections import defaultdict
import re
import numpy as np
import sys
import seaborn as sns
import matplotlib.pyplot as plt

pal = sns.color_palette()


sys.path.insert(0, '../../base_codes')
sys.path.insert(0, '../../data_specific_codes')
sys.path.insert(0, '../../utility_codes')


from RE_init import *
from main_functions import *
from utility_functions import *

def read_df_rel():
    #based_dir = '../../../../data/GoodReads/'
    based_dir = '../../../../data/Tweets/'
    file_input_name = 'merged.csv'
    file_input = based_dir + file_input_name    
    ff = open(file_input)
    delim=","
    df = pd.read_csv(file_input,delimiter=delim,header=0)        
    return df

df_rels = read_df_rel()
#rename a column
df_rels.rename(columns = {'Replaced Version of Main Tweet':'text'}, inplace = True)
#take unique tweets
df_unique = df_rels.drop_duplicates('text', inplace = False)
df_unique.reset_index(inplace=True)
#make the text to be lower case
df_unique = df_unique.apply(lambda x: x.astype(str).str.lower())

In [48]:
df_sample = df_unique.sample(100)

In [49]:
#import banks
df_banks = pd.read_csv('../../../../data/Tweets/Evaluation/banks_freq.csv',delimiter=",",header=0)     
#import merchants 
df_merchants = pd.read_csv('../../../../data/Tweets/Evaluation/merchants_freq.csv', delimiter=",", header=0)

In [50]:
df_mobile_payments = pd.DataFrame(["applepay","googlewallet","samsungpay"],columns=["mp"])

In [51]:
dict_3categ_tweet_ind = defaultdict(list)

In [52]:
import time
start_time = time.time()
for ind, row in df_unique.iterrows():#df_sample.iterrows():#
    text = row["text"]
    has_bank, has_merch, has_mp = False,False,False
    for tmp,b in df_banks.iterrows():
        if b["Bank"] in text:
            has_bank = True
            break
    for tmp, merch in df_merchants.iterrows():
        if merch["Merchant"] in text:
            has_merch = True
            break
    for tmp, mp in df_mobile_payments.iterrows():
        if mp["mp"] in text:
            has_mp = True
            break
    if has_mp and has_merch:
        dict_3categ_tweet_ind["mp_merch"].append(ind)
    if has_merch and has_bank:
        dict_3categ_tweet_ind["bank_merch"].append(ind)
    if has_bank and has_mp:
        dict_3categ_tweet_ind["bank_mp"].append(ind)
        
print("--- %s seconds ---" % (time.time() - start_time))

--- 7110.13353181 seconds ---

In [53]:
dict_3categ_tweet_ind

defaultdict(list,
            {'bank_merch': [103,
              310,
              631,
              736,
              737,
              741,
              927,
              945,
              993,
              1069,
              1344,
              1345,
              1362,
              1376,
              1473,
              1547,
              1721,
              1813,
              1821,
              1877,
              1909,
              2008,
              2665,
              3252,
              3257,
              3302,
              3435,
              3883,
              3954,
              3988,
              3989,
              3990,
              3991,
              3992,
              3993,
              3994,
              3995,
              3996,
              3997,
              3999,
              4003,
              4045,
              4357,
              4591,
              4598,
              4643,
              4690,
              4695,
              4697,
              4699,
              4705,
              4706,
              4714,
              4718,
              4721,
              4728,
              4729,
              4730,
              4818,
              4918,
              4940,
              4959,
              5036,
              5145,
              5246,
              5426,
              5482,
              5637,
              5829,
              5836,
              5980,
              5994,
              6210,
              6218,
              6227,
              6231,
              6249,
              6268,
              6269,
              6270,
              6271,
              6274,
              6278,
              6280,
              6281,
              6299,
              6302,
              6303,
              6304,
              6307,
              6313,
              6314,
              6316,
              6348,
              6366,
              6386,
              6387,
              6388,
              6400,
              6479,
              6528,
              6605,
              6747,
              6848,
              6939,
              7271,
              7272,
              8000,
              8219,
              8233,
              8483,
              9025,
              9192,
              9285,
              9297,
              9298,
              9435,
              9906,
              9932,
              9975,
              9987,
              10047,
              10139,
              10229,
              10261,
              10332,
              10409,
              10626,
              11009,
              11083,
              11343,
              11383,
              11386,
              11412,
              11416,
              11420,
              11424,
              11433,
              11631,
              11782,
              12008,
              12118,
              12678,
              12769,
              13012,
              13206,
              13441,
              13481,
              13547,
              13574,
              13596,
              13662,
              13703,
              13732,
              13970,
              14463,
              15385,
              16927,
              17135,
              18037,
              18219,
              18231,
              18343,
              18609,
              18908,
              19032,
              19059,
              19096,
              19134,
              19181,
              19478,
              19534,
              19649,
              19694,
              19772,
              19812,
              19856,
              19866,
              19946,
              20036,
              20072,
              20089,
              20177,
              20707,
              20774,
              21046,
              21103,
              21171,
              21550,
              21559,
              21763,
              21853,
              21931,
              21975,
              21991,
              22082,
              22130,
              22406,
              22516,
              22748,
              22835,
              22841,
              22904,
              23126,
              23231,
              23294,
              23317,
              23622,
              23836,
              23841,
              23925,
              24326,
              24350,
              24988,
              25135,
              25138,
              25157,
              25263,
              25346,
              25409,
              25635,
              25964,
              25996,
              26227,
              26293,
              26310,
              26323,
              26425,
              26430,
              26583,
              26640,
              26703,
              26791,
              26928,
              26938,
              26964,
              27326,
              27481,
              27886,
              28018,
              28042,
              28092,
              28541,
              28547,
              28576,
              28580,
              28672,
              28765,
              28768,
              28885,
              28898,
              28926,
              28931,
              28992,
              29049,
              29106,
              29215,
              29343,
              29423,
              29497,
              29516,
              29836,
              30196,
              30259,
              30401,
              30477,
              30487,
              30513,
              30539,
              30563,
              30666,
              30691,
              30696,
              30859,
              31147,
              31206,
              31297,
              31437,
              31454,
              31492,
              31599,
              31604,
              31742,
              31926,
              32004,
              32018,
              32315,
              32516,
              32617,
              32751,
              32757,
              32841,
              32844,
              32845,
              32847,
              32906,
              32990,
              33118,
              33259,
              33312,
              33317,
              33424,
              33508,
              33639,
              33672,
              33882,
              34020,
              34029,
              34074,
              34167,
              34380,
              34478,
              34497,
              34501,
              34930,
              35281,
              35401,
              35456,
              35754,
              35906,
              35911,
              36044,
              36174,
              36321,
              36658,
              36677,
              36798,
              36841,
              36924,
              36949,
              37100,
              37153,
              37279,
              37428,
              37451,
              37777,
              38033,
              38045,
              38127,
              38181,
              38365,
              38390,
              38397,
              38554,
              38633,
              38806,
              38833,
              38836,
              38859,
              38912,
              38937,
              39106,
              39167,
              39225,
              39271,
              39285,
              39325,
              39652,
              39763,
              39941,
              39960,
              39967,
              39968,
              40164,
              40257,
              40260,
              40271,
              40349,
              40361,
              40500,
              40780,
              40861,
              40886,
              40904,
              40948,
              40968,
              41013,
              41091,
              41209,
              41667,
              41697,
              41789,
              41911,
              41940,
              41980,
              42002,
              42346,
              42388,
              42390,
              42466,
              42641,
              43001,
              43132,
              43359,
              43437,
              43439,
              43530,
              43552,
              43690,
              43718,
              43787,
              43818,
              43998,
              44043,
              44089,
              44162,
              44333,
              44398,
              44454,
              44539,
              44558,
              44705,
              44719,
              44746,
              44959,
              44977,
              44998,
              45260,
              45277,
              45348,
              45360,
              45395,
              45695,
              46647,
              46887,
              47159,
              47251,
              47588,
              47689,
              47740,
              47741,
              47852,
              47992,
              48005,
              48041,
              48086,
              48239,
              48412,
              48637,
              48734,
              48735,
              48766,
              48770,
              49207,
              49245,
              49252,
              49383,
              49728,
              49897,
              49946,
              49949,
              50165,
              50169,
              50184,
              50273,
              50320,
              50324,
              50484,
              50643,
              50675,
              50678,
              51232,
              51248,
              51272,
              51312,
              51370,
              51422,
              51471,
              51494,
              51507,
              51531,
              51599,
              51643,
              51768,
              51838,
              52072,
              52210,
              52245,
              52276,
              52278,
              52299,
              52309,
              52310,
              52319,
              52322,
              52323,
              52324,
              52333,
              52355,
              52357,
              52358,
              52388,
              52412,
              52447,
              52524,
              52705,
              52844,
              52915,
              52923,
              53004,
              53170,
              53300,
              53420,
              53442,
              53473,
              53552,
              53571,
              53604,
              53624,
              53630,
              53693,
              53696,
              53725,
              53739,
              53759,
              53793,
              54035,
              54056,
              54114,
              54126,
              54140,
              54189,
              54276,
              54287,
              54307,
              54309,
              54322,
              54557,
              54649,
              54677,
              54716,
              54720,
              54809,
              54929,
              54991,
              55044,
              55116,
              55581,
              55642,
              55927,
              55933,
              56059,
              56088,
              56160,
              56200,
              56206,
              56218,
              56477,
              56562,
              56565,
              56603,
              56723,
              56902,
              57117,
              57175,
              57185,
              57270,
              57282,
              57333,
              57508,
              57565,
              57736,
              58035,
              58242,
              58276,
              58334,
              58400,
              58473,
              58493,
              58497,
              58534,
              58582,
              58592,
              58788,
              59051,
              59210,
              59273,
              59657,
              59973,
              60015,
              60078,
              60145,
              60630,
              60634,
              60635,
              60724,
              60912,
              60949,
              60952,
              61260,
              61336,
              61429,
              61759,
              61768,
              61934,
              61938,
              61948,
              61970,
              62189,
              62646,
              62680,
              62817,
              62915,
              62916,
              62917,
              62918,
              62922,
              62931,
              62943,
              62958,
              62968,
              62971,
              63210,
              63286,
              63336,
              63357,
              63394,
              63418,
              63720,
              63792,
              63827,
              63845,
              63973,
              64055,
              64105,
              64121,
              64219,
              64266,
              64403,
              64464,
              64514,
              64601,
              64619,
              64845,
              64936,
              64944,
              65040,
              65107,
              65175,
              65200,
              65233,
              65248,
              65273,
              65279,
              65332,
              65412,
              65594,
              65596,
              65608,
              65671,
              65827,
              65869,
              66053,
              66271,
              66275,
              66292,
              66329,
              66372,
              66475,
              66477,
              66666,
              66760,
              66815,
              66821,
              66896,
              67049,
              67081,
              67115,
              67351,
              67681,
              67699,
              68008,
              68198,
              68215,
              68262,
              68374,
              68499,
              68561,
              68631,
              68729,
              68772,
              68788,
              68793,
              68950,
              69144,
              69313,
              69363,
              69414,
              69423,
              69470,
              69499,
              69594,
              69598,
              69605,
              69682,
              69873,
              69922,
              70096,
              70127,
              70215,
              70312,
              70324,
              70327,
              70510,
              70511,
              70701,
              70732,
              71096,
              71149,
              71160,
              71168,
              71183,
              71185,
              71211,
              71217,
              71224,
              71245,
              71264,
              71344,
              71380,
              71480,
              71553,
              71615,
              71848,
              71849,
              72221,
              72329,
              72335,
              72404,
              72914,
              72958,
              73293,
              73303,
              73316,
              73337,
              73356,
              73482,
              73697,
              73871,
              74007,
              74009,
              74060,
              74065,
              74086,
              74175,
              74513,
              74537,
              74577,
              74586,
              74856,
              74873,
              74914,
              74936,
              75001,
              75402,
              75413,
              75426,
              75440,
              75714,
              75834,
              76306,
              76345,
              76415,
              76417,
              76735,
              76763,
              76952,
              76954,
              76967,
              77072,
              77113,
              77226,
              77249,
              77622,
              77766,
              77911,
              78357,
              78498,
              78551,
              78720,
              79538,
              79664,
              80199,
              80206,
              80208,
              80235,
              80275,
              80298,
              80754,
              81034,
              81044,
              81081,
              81086,
              81124,
              81146,
              81163,
              81168,
              81248,
              81254,
              81257,
              81286,
              81391,
              81452,
              81500,
              81520,
              81529,
              81541,
              81751,
              81758,
              81774,
              81828,
              82064,
              82152,
              82299,
              82363,
              82389,
              82413,
              82417,
              82619,
              82694,
              82750,
              82910,
              83070,
              83077,
              83137,
              83656,
              83743,
              83758,
              83936,
              84297,
              84436,
              84458,
              84472,
              84478,
              84574,
              84666,
              84687,
              84702,
              84703,
              84704,
              84707,
              84709,
              84710,
              84711,
              84712,
              84717,
              84718,
              84723,
              84725,
              84726,
              84731,
              84733,
              84734,
              84737,
              84741,
              84742,
              84743,
              84744,
              84745,
              84750,
              84755,
              84756,
              84758,
              84759,
              84760,
              84761,
              84763,
              84764,
              84766,
              84767,
              84768,
              84770,
              84771,
              84772,
              84773,
              84774,
              84775,
              84776,
              84777,
              84778,
              84779,
              84780,
              84781,
              84782,
              84783,
              84785,
              84786,
              84789,
              84792,
              84793,
              84795,
              84797,
              84801,
              84802,
              84803,
              84804,
              84805,
              84806,
              84809,
              84810,
              84818,
              84821,
              84822,
              84823,
              84826,
              84827,
              84831,
              84833,
              84842,
              84843,
              84844,
              84845,
              84846,
              84847,
              84848,
              84853,
              84854,
              84855,
              84858,
              84859,
              84862,
              84863,
              84864,
              84865,
              84866,
              84867,
              84868,
              84869,
              84870,
              84871,
              84874,
              84876,
              84881,
              84882,
              84884,
              84885,
              84886,
              84887,
              84888,
              84889,
              84892,
              84893,
              84894,
              84895,
              84897,
              84898,
              84899,
              84900,
              84901,
              84903,
              84904,
              84905,
              84906,
              84908,
              84909,
              84910,
              84911,

In [54]:
df_rels.iloc[500235]["text"]

', kfc, And Chillis Now Accepting ApplePay invest finance _'

In [55]:
df_sample

,index,tweet_id,tweet_posted_time,tweet_author_id,tweet_author_location,tweet_country,city,tweet_lang,lat,lon,...,Main Tweet,Main Entities,Main Hashtags,Alternative Possibility,Side Tweets,Related to,Retweeted From,Feed,Audience,text
14815,39919,2005:620702298088456192,2015-07-13t21:12:14.000z,1331736728,"england, united kingdom.",nan,nan,en,nan,nan,...,soooooo apple pay tomorrow apparently.. let's ...,set(),set(),set(),set(),set(),nan,set(),set(),soooooo applepay tomorrow apparently.. let's h...
176514,452432,2005:649398089053274112,2015-10-01t01:39:04.000z,2640014526,usa,nan,nan,en,nan,nan,...,cell phones deals &gt;&gt;,set(),{'deals'},set(),{' 812 for sony xperia z1s t-mobile wallet fli...,set(),nan,set(),set(),cell phones deals &gt;&gt;
148341,383591,2005:644316017481633793,2015-09-17t01:04:44.000z,2661644340,nan,nan,nan,en,nan,nan,...,gurps_singh: amrinder01 oneplustwo don't have ...,set(),"{'androidpay', 'oneplustwo', 'applepay'}",set(),set(),set(),nan,{'rt'},set(),gurps_singh: amrinder01 oneplustwo do not have...
67889,168088,2005:626418364483772416,2015-07-29t15:45:51.000z,576619818,nan,nan,nan,en,nan,nan,...,i am having trouble setting up my bank card on...,set(),set(),{'askbankofscot i am having trouble setting up...,set(),set(),nan,set(),{'askbankofscot'},i am having trouble setting up my bank card on...
170892,439706,2005:648573012443308032,2015-09-28t19:00:30.000z,254879928,"12 offices, 4 countries",nan,nan,en,nan,nan,...,paypal launches new mobile card reader for and...,{'ruthreader'},"{'androidpay', 'applepay'}",set(),set(),set(),nan,set(),set(),paypal launches new mobile card reader for and...
5440,15004,2005:618018340901158912,2015-07-06t11:27:09.000z,18213384,nan,nan,nan,en,nan,nan,...,"over 400,000 visa payment units are contactles...",set(),"{'applepay', 'nfc'}",set(),set(),set(),nan,set(),set(),"over 400,000 visa payment units are contactles..."
127436,332446,2005:639858267720552448,2015-09-04t17:51:13.000z,1469236170,west coast best coast,nan,nan,en,nan,nan,...,fuck me friday deal! $20 google wallet = 120+ ...,set(),set(),set(),set(),set(),nan,set(),set(),fuck me friday deal! $20 googlewallet = 120+ b...
5369,14739,2005:618010637319319552,2015-07-06t10:56:32.000z,27749294,seattle,nan,nan,en,nan,nan,...,apple has filed a patent that could kill off m...,set(),set(),set(),set(),set(),nan,{'sai'},set(),apple has filed a patent that could kill off m...
143128,372485,2005:643469887864705024,2015-09-14t17:02:31.000z,20856311,chicago,nan,nan,en,nan,nan,...,two things that would make southwestair even b...,"{'southwestair', 'apple'}",{'applepay'},set(),set(),{'justsayin'},nan,set(),set(),two things that would make southwestair even b...
20173,53572,2005:620866952634998784,2015-07-14t08:06:31.000z,143025236,london,nan,nan,en,nan,nan,...,pay launches in uk - how and where to use it s...,"{'emmalyds', 'thomaspower', 'nathan_jr_eno', '...",set(),{'apple pay launches in uk - how and where to ...,set(),{'apple'},stevewal63,{'video'},set(),pay launches in uk - how and where to use it s...
146541,380024,2005:644111186863202304,2015-09-16t11:30:48.000z,267218058,scotland,nan,nan,en,nan,nan,...,you can use apple pay in mcdonalds. apple pay....,set(),set(),set(),set(),set(),nan,set(),set(),you can use applepay in mcdonalds. applepay. i...
170618,438861,2005:648559412735549440,2015-09-28t18:06:28.000z,27533028,puerto rico,nan,nan,en,nan,nan,...,when my capitalone card is going to be availab...,{'capitalone'},{'asap'},set(),set(),set(),nan,set(),set(),when my capitalone card is going to be availab...
8966,24739,2005:618820355944284160,2015-07-08t16:34:04.000z,14687193,nyc,nan,nan,en,nan,nan,...,apple pay to launch outside us next week: appl...,set(),set(),set(),set(),set(),nan,set(),set(),applepay to launch outside us next week: apple...
168074,430324,2005:648267580923318273,2015-09-27t22:46:50.000z,278231269,huddersfield,nan,nan,en,nan,nan,...,when is barclays going live with apple pay?? i...,set(),set(),{'when is barclays going live with apple pay??...,set(),set(),nan,set(),{'barclaysuk'},when is barclays going live with applepay?? i ...
146678,380235,2005:644136421276545024,2015-09-16t13:11:04.000z,2413725913,nan,nan,nan,en,nan,nan,...,discover it card + apple pay,set(),set(),set(),set(),set(),nan,set(),set(),discover it card + applepay
72921,180234,2005:627760339321532416,2015-08-02t08:38:22.000z,297040570,london & essex,nan,nan,en,nan,nan,...,congratulations! you have embarked on the futu...,{'tim_cook'},{'applepay'},{'essexsu congratulations! you have embarked o...,set(),set(),nan,set(),{'essexsu'},congratulations! you have embarked on the futu...
52695,131625,2005:623104058702872576,2015-07-20t12:15:58.000z,2661644340,nan,nan,nan,en,nan,nan,...,jfeijoocundy: rt dc_copeland: uk banks are fai...,set(),set(),{'jfeijoocundy: rt dc_copeland: uk banks are f...,set(),"{'bankingnews', 'applepay'}",nan,{'rt'},set(),jfeijoocundy: rt dc_copeland: uk banks are fai...
45157,111966,2005:621724873036034048,2015-07-16t16:55:35.000z,1399113342,bandung,nan,nan,en,nan,nan,...,"how to use it as an iphone camera remote, pay ...",set(),set(),set(),set(),{'uncategor_'},nan,{'apple watch tips'},set(),"how to use it as an iphone camera remote, pay ..."
155461,399397,2005:645628348199075841,2015-09-20t15:59:28.000z,62911603,usa - community guidelines,nan,nan,en,nan,nan,...,"hi steven, please contact our digital assist t...",set(),set(),"{'nonopino10 hi steven, please contact our dig...",set(),set(),nan,set(),{'nonopino10'},"hi steven, please contact our digital assist t..."
97333,253069,2005:632580012261134336,2015-08-15t15:50:02.000z,16135892,"london, uk",nan,nan,en,nan,nan,...,"no, i guess thats a new frontier. i guess too ...",set(),set(),"{'reneritchie no, i guess thats a new frontier...",set(),set(),nan,set(),{'reneritchie'},"no, i guess thats a new frontier. i guess too ..."
8000,22474,2005:618522917232619520,2015-07-07t20:52:09.000z,790309178,nan,nan,nan,en,nan,nan,...,hi i hear that barclays is not going to adopt ...,set(),set(),"{""barclaysukhelp hi i hear that barclays is no...",set(),set(),nan,set(),{'barclaysukhelp'},hi i hear that barclays is not going to adopt ...
176491,452398,2005:649396293165563904,2015-10-01t01:31:56.000z,17040627,"houston, tx",nan,nan,en,nan,nan,...,"samsung pay, i am disappoint. four banks accep...",set(),set(),set(),set(),set(),nan,set(),set(),"samsungpay, i am disappoint. four banks accept..."
113362,297562,2005:636522483496058880,2015-08-26t12:56:00.000z,2556969954,london and throughout the uk,nan,nan,en,nan,nan,...,dont get too excited about apple pay,set(),set(),set(),set(),{'applepay'},nan,set(),set(),dont get too excited about applepay
3157,6326,2005:617232501216555008,2015-07-04t07:24:30.000z,3303315742,"philadelphia, pa",nan,nan,en,nan,nan,...,so spoil me pigs. gift cards: goddessssyegmail...,set(),set(),{'hotterthanyourwife so spoil me pigs.\n\ngift...,set(),{'hotterthanyourwife'},nan,set(),set(),so spoil me pigs. gift cards: goddessssyegmail...
80042,198992,2005:629545435800055808,2015-08-07t06:51:42.000z,134637510,san francisco bay area,nan,nan,en,nan,nan,...,mobile wallet takes another step towards mobil...,set(),set(),{'paypal mobile wallet takes another step towa...,set(),set(),nan,set(),{'paypal'},mobile wallet takes another step towards mobil...
10267,27685,2005:619281846954672132,2015-07-09t23:07:52.000z,201914052,sydney australia,nan,nan,en,nan,nan,...,wonder if apple users/devotees realise its dev...,set(),"{'accc', 'applepay', 'apple'}",{'wonder if apple users/devotees realise its d...,set(),set(),nan,set(),set(),wonder if apple users/devotees realise its dev...
19689,52520,2005:620863224880177156,2015-07-14t07:51:42.000z,20145055,manchester,nan,nan,en,nan,nan,...,ooooo applepay coming later this july with hsb...,set(),{'applepay'},"{""ooooo applepay coming later this july with h...",set(),set(),nan,set(),set(),ooooo applepay coming later this july with hsb...
163659,421908,2005:647174553127526400,2015-09-24t22:23:32.000z,147932302,nan,nan,nan,en,nan,nan,...,"unfortunately, we can't access accounts to see...",set(),set(),"{""screening9912 unfortunately, we can't access...",set(),set(),nan,set(),{'screening9912'},"unfortunately, we cannot access accounts to se..."
179666,458622,2005:650093882596659200,2015-10-02t23:43:54.000z,15227849,"palo alto, ca",nan,nan,en,nan,nan,...,"apple pay works in a mobile native app world, ...",set(),set(),{'igor apple pay works in a mobile native app ...,set(),set(),nan,set(),{'igor'},"applepay works in a mobile native app world, n..."
138166,360818,2005:642337520261419008,2015-09-11t14:02:53.000z,21251449,uk,nan,nan,en,nan,nan,...,"that's good, but isn't the applepay limit now 30?",set(),set(),"{""natwest_help that's good, but isn't the appl...",set(),set(),nan,set(),{'natwest_help'},"that's good, but is not the applepay limit now..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167425,429330,2005:648143849265713153,2015-09-27t14:35:10.000z,14616957,nyc/nj,nan,nan,en,nan,nan,...,just used samsung pay at walmart. guess they c...,set(),set(),set(),set(),set(),nan,set(),set(),just used samsungpay at walmart. guess they ca...
177697,454961,2005:649650914081398784,2015-10-01t18:23:42.000z,375003,marin / sf,nan,nan,en,nan,nan,...,apple pay on apple watch is the most apple thi...,set(),set(),set(),set(),set(),nan,set(),set(),applepay on apple watch is the most apple thin...
49336,123396,2005:622173649945145345,2015-07-17t22:38:52.000z,16478335,london - doha,nan,nan,en,nan,nan,...,1st impressions of using apple pay on tube aft...,set(),set(),set(),set(),set(),nan,set(),set(),1st impressions of using applepay on tube afte...
182181,463782,2005:650986172911591424,2015-10-05t10:49:33.000z,32468305,nan,nan,nan,en,nan,nan,...,any news on when amex uk will support in-app a...,set(),set(),{'askamexuk any news on when amex uk will supp...,set(),set(),nan,set(),{'askamexuk'},any news on when amex uk will support in-app a...
89991,229274,2005:631845598891651072,2015-08-13t15:11:44.000z,2507032213,nan,nan,nan,en,nan,nan,...,samsung pay is officially launched with the ne...,set(),{'unpacked'},set(),set(),set(),nan,set(),set(),samsungpay is officially launched with the new...
122626,321581,2005:638690347166662656,2015-09-01t12:30:19.000z,20507237,"nottingham, uk",nan,nan,en,nan,nan,...,if you're a fan of contactless payments - the ...,set(),set(),set(),set(),set(),nan,set(),set(),if you're a fan of contactless payments - the ...
180052,459433,2005:650290593512452096,2015-10-03t12:45:33.000z,471934058,portishead bristol,nan,nan,en,nan,nan,...,just used apple pay for the first time. it's s...,set(),set(),set(),set(),set(),nan,set(),set(),just used applepay for the first time. it's su...
63710,158528,2005:625776288079417344,2015-07-27t21:14:28.000z,47596755,london,nan,nan,en,nan,nan,...,can you please sign this petition and share it,set(),set(),set(),set(),"{'barclaysgate', 'applepay'}",nan,set(),"{'blusmoke', 'barclaysuk'}",can you please sign this petition and share it
125843,329106,2005:639426385564573696,2015-09-03t13:15:04.000z,121509154,nederland,nan,nan,nl,nan,nan,...,weg met privacy &amp;amp; een hekel aangeldter...,set(),set(),set(),set(),set(),nan,{'ov-chipkaart'},set(),weg met privacy &amp;amp; een hekel aangeldter...
65400,162559,2005:625995568578326528,2015-07-28t11:45:48.000z,2450414006,internet,nan,nan,en,nan,nan,...,hsbc &amp; first direct now support apple pay:...,set(),set(),{'btc hsbc &amp; first direct now support appl...,set(),"{'btc', 'bitcoin'}",nan,set(),set(),hsbc &amp; first direct now support applepay: ...
133703,347026,2005:641880129115848704,2015-09-10t07:45:22.000z,1950925981,global,nan,nan,en,nan,nan,...,thinking beyond retail: contactless payments a...,set(),set(),set(),set(),set(),nan,{'apple pay'},set(),thinking beyond retail: contactless payments a...
84523,210088,2005:631078064647241729,2015-08-11t12:21:50.000z,237212651,north east england,nan,nan,en,nan,nan,...,"hi rob, apple pay works on metro.",set(),set(),"{'robertsammons hi rob, apple pay works on met...",set(),set(),nan,set(),{'robertsammons'},"hi rob, applepay works on metro."
120339,315787,2005:638346223959834624,2015-08-31t13:42:54.000z,834242154,nan,nan,nan,en,nan,nan,...,the daily meal food truck-goers will soon be a...,set(),set(),set(),set(),set(),nan,set(),set(),the daily meal food truck-goers will soon be a...
34022,88039,2005:621043241576734720,2015-07-14t19:47:01.000z,349540065,nan,nan,nan,en,nan,nan,...,the real answer to this is - contact telephone...,set(),set(),{'natwest_help the real answer to this is - co...,set(),set(),nan,set(),{'natwest_help'},the real answer to this is - contact telephone...
199896,519381,2005:653930406841085952,2015-10-13t13:48:53.000z,55190734,nan,nan,nan,nl,nan,nan,...,en connexxion kunnen jullie nickyverbeek helpe...,"{'connexxion', 'nickyverbeek'}",set(),{'ns_online en connexxion kunnen jullie nickyv...,set(),set(),nan,set(),{'ns_online'},en connexxion kunnen jullie nickyverbeek helpe...
66577,165207,2005:626118383495421952,2015-07-28t19:53:49.000z,30507583,"cardiff/durham, uk",nan,nan,en,nan,nan,...,great to finally have my hsbc cards added to a...,set(),set(),set(),set(),set(),nan,set(),set(),great to finally have my hsbc cards added to a...
31737,81903,2005:620993355434954752,2015-07-14t16:28:48.000z,278083839,"oakland, california",nan,nan,en,nan,nan,...,surprised tomwarren didnt call apple pay by it...,{'tomwarren'},set(),{'reckless surprised tomwarren didnt call appl...,set(),set(),nan,set(),{'reckless'},surprised tomwarren didnt call applepay by its...
147064,381037,2005:644176348597088257,2015-09-16t15:49:44.000z,61765642,london,nan,nan,en,nan,nan,...,why arent contactless payments in cabs? how ab...,set(),set(),set(),set(),set(),nan,set(),"{'savetaxi', 'lbc', 'disabilitylab'}",why arent contactless payments in cabs? how ab...
60623,150569,2005:624753669808984064,2015-07-25t01:30:56.000z,3390907138,nan,nan,nan,en,nan,nan,...,my wish list is getting a bit too long! findom...,set(),"{'fetishfriday', 'findomfriday'}",{'my wish list is getting a bit too long!\nfin...,set(),"{'tribute', 'payday', 'findom'}",nan,set(),set(),my wish list is getting a bit too long! findom...
170378,438033,2005:648547677966307328,2015-09-28t17:19:50.000z,28595634,"t: 43.658762,-79.378149",nan,nan,en,nan,nan,...,everything you need to know about samsung pay:...,set(),set(),{'trend everything you need to know about sams...,set(),"{'trend', 'digital'}",nan,set(),set(),everything you need to know about samsungpay: ...
159338,410524,2005:646349842042761217,2015-09-22t15:46:25.000z,24378196,"cambridge, uk",nan,nan,en,nan,nan,...,"this is why paypal etc, apple pay etc have dev...",set(),set(),"{'laurakbuzz this is why paypal etc, apple pay...",set(),set(),nan,set(),{'laurakbuzz'},"this is why paypal etc, applepay etc have deve..."
105317,275448,2005:634175003194454016,2015-08-20t01:27:57.000z,2661644340,nan,nan,nan,en,nan,nan,...,aundreaqiz: $grnh greengrotech,set(),set(),set(),{' applepay draghi be sure to look up add this'},set(),nan,{'rt'},set(),aundreaqiz: $grnh greengro
165248,425177,2005:647509282536226817,2015-09-25t20:33:37.000z,871313263,"cardiff, wales",nan,nan,en,nan,nan,...,"awesome, will pop in branch tomorrow. recently...",set(),{'barclays'},"{'natwest_help awesome, will pop in branch tom...",set(),{'applepay'},nan,set(),{'natwest_help'},"awesome, will pop in branch tomorrow. recently..."
88900,225458,2005:631640014447898624,2015-08-13t01:34:49.000z,2661644340,nan,nan,nan,en,nan,nan,...,advisermag: everything you want to know about ...,set(),set(),set(),set(),"{'entrepreneur', 'business'}",nan,{'rt'},set(),advisermag: everything you want to know about ...
80678,200037,2005:629666739584937984,2015-08-07t14:53:44.000z,16600476,"fulham, london",united kingdom,city of london,en,nan,nan,...,that was my original point: most retailers alr...,set(),{'applepay'},{'bygeoffw that was my original point: most re...,set(),set(),nan,set(),{'bygeoffw'},that was my original point: most retailers alr...
79351,197058,2005:629331265032843265,2015-08-06t16:40:40.000z,104945339,"new city, ny",nan,nan,en,nan,nan,...,interesting analysis on the usage rates of mob...,set(),{'mobilepayment'},{'interesting analysis on the usage rates of m...,set(),{'nfc'},nan,set(),set(),interesting analysis on the usage rates of mob...
117825,310777,2005:637344571391889408,2015-08-28t19:22:41.000z,2661644340,nan,nan,nan,en,nan,nan,...,tragweshili1984: jonp82: so i used applepay to...,set(),{'applepay'},set(),set(),"{'addicted', 'tapibook', 'tb'}",nan,{'rt'},set(),tragweshili1984: jonp82: so i used applepay to...
109800,288373,2005:635265729244364800,2015-08-23t01:42:07.000z,3068098601,nan,nan,nan,en,nan,nan,...,rumored iphone 6c will feature touch id and ap...,set(),set(),set(),set(),set(),nan,set(),set(),rumored iphone 6c will feature touch id and ap...
171951,442692,2005:648670994169745408,2015-09-29t01:29:51.000z,3024245814,nan,nan,nan,en,nan,nan,...,wireless verifone vx680 emv / apple pay ready ...,set(),set(),set(),set(),set(),nan,set(),set(),wireless verifone vx680 emv / applepay ready c...
5509,15139,2005:618027936176828418,2015-07-06t12:05:17.000z,616149508,toronto,nan,nan,en,nan,nan,...,apple pay to launch in the uk july 14 mobile,set(),set(),{'apple pay to launch in the uk july 14'},set(),set(),nan,set(),set(),applepay to launch in the uk july 14 mobile

In [ ]:
#df.iloc[[1,3],:]

In [79]:
for ind, row in df_unique.iterrows():
    if ind == 103:
        print row["text"]
        break

when your setting up your googlewallet &amp; paypal accounts for your own business but bitches claim you do not get money __ tuhhyouwishhoe

In [80]:
df_unique.iloc[[103],:]

,index,tweet_id,tweet_posted_time,tweet_author_id,tweet_author_location,tweet_country,city,tweet_lang,lat,lon,...,Main Tweet,Main Entities,Main Hashtags,Alternative Possibility,Side Tweets,Related to,Retweeted From,Feed,Audience,text
103,154,2005:616090389297147904,2015-07-01t03:46:09.000z,98700843,around !,nan,nan,en,nan,nan,...,when your setting up your google wallet &amp; ...,set(),set(),"{""when your setting up your google wallet &amp...",set(),set(),nan,set(),set(),when your setting up your googlewallet &amp; p...

In [56]:
import pickle
pickle.dump( dict_3categ_tweet_ind, open("../../../../data/Tweets/Evaluation/dict_3categ_tweet_ind.pkl", "wb" ) )

In [77]:
dict_3categ_tweet_ind["bank_merch"]

[103,
 310,
 631,
 736,
 737,
 741,
 927,
 945,
 993,
 1069,
 1344,
 1345,
 1362,
 1376,
 1473,
 1547,
 1721,
 1813,
 1821,
 1877,
 1909,
 2008,
 2665,
 3252,
 3257,
 3302,
 3435,
 3883,
 3954,
 3988,
 3989,
 3990,
 3991,
 3992,
 3993,
 3994,
 3995,
 3996,
 3997,
 3999,
 4003,
 4045,
 4357,
 4591,
 4598,
 4643,
 4690,
 4695,
 4697,
 4699,
 4705,
 4706,
 4714,
 4718,
 4721,
 4728,
 4729,
 4730,
 4818,
 4918,
 4940,
 4959,
 5036,
 5145,
 5246,
 5426,
 5482,
 5637,
 5829,
 5836,
 5980,
 5994,
 6210,
 6218,
 6227,
 6231,
 6249,
 6268,
 6269,
 6270,
 6271,
 6274,
 6278,
 6280,
 6281,
 6299,
 6302,
 6303,
 6304,
 6307,
 6313,
 6314,
 6316,
 6348,
 6366,
 6386,
 6387,
 6388,
 6400,
 6479,
 6528,
 6605,
 6747,
 6848,
 6939,
 7271,
 7272,
 8000,
 8219,
 8233,
 8483,
 9025,
 9192,
 9285,
 9297,
 9298,
 9435,
 9906,
 9932,
 9975,
 9987,
 10047,
 10139,
 10229,
 10261,
 10332,
 10409,
 10626,
 11009,
 11083,
 11343,
 11383,
 11386,
 11412,
 11416,
 11420,
 11424,
 11433,
 11631,
 11782,
 12008,
 12118,
 12678,
 12769,
 13012,
 13206,
 13441,
 13481,
 13547,
 13574,
 13596,
 13662,
 13703,
 13732,
 13970,
 14463,
 15385,
 16927,
 17135,
 18037,
 18219,
 18231,
 18343,
 18609,
 18908,
 19032,
 19059,
 19096,
 19134,
 19181,
 19478,
 19534,
 19649,
 19694,
 19772,
 19812,
 19856,
 19866,
 19946,
 20036,
 20072,
 20089,
 20177,
 20707,
 20774,
 21046,
 21103,
 21171,
 21550,
 21559,
 21763,
 21853,
 21931,
 21975,
 21991,
 22082,
 22130,
 22406,
 22516,
 22748,
 22835,
 22841,
 22904,
 23126,
 23231,
 23294,
 23317,
 23622,
 23836,
 23841,
 23925,
 24326,
 24350,
 24988,
 25135,
 25138,
 25157,
 25263,
 25346,
 25409,
 25635,
 25964,
 25996,
 26227,
 26293,
 26310,
 26323,
 26425,
 26430,
 26583,
 26640,
 26703,
 26791,
 26928,
 26938,
 26964,
 27326,
 27481,
 27886,
 28018,
 28042,
 28092,
 28541,
 28547,
 28576,
 28580,
 28672,
 28765,
 28768,
 28885,
 28898,
 28926,
 28931,
 28992,
 29049,
 29106,
 29215,
 29343,
 29423,
 29497,
 29516,
 29836,
 30196,
 30259,
 30401,
 30477,
 30487,
 30513,
 30539,
 30563,
 30666,
 30691,
 30696,
 30859,
 31147,
 31206,
 31297,
 31437,
 31454,
 31492,
 31599,
 31604,
 31742,
 31926,
 32004,
 32018,
 32315,
 32516,
 32617,
 32751,
 32757,
 32841,
 32844,
 32845,
 32847,
 32906,
 32990,
 33118,
 33259,
 33312,
 33317,
 33424,
 33508,
 33639,
 33672,
 33882,
 34020,
 34029,
 34074,
 34167,
 34380,
 34478,
 34497,
 34501,
 34930,
 35281,
 35401,
 35456,
 35754,
 35906,
 35911,
 36044,
 36174,
 36321,
 36658,
 36677,
 36798,
 36841,
 36924,
 36949,
 37100,
 37153,
 37279,
 37428,
 37451,
 37777,
 38033,
 38045,
 38127,
 38181,
 38365,
 38390,
 38397,
 38554,
 38633,
 38806,
 38833,
 38836,
 38859,
 38912,
 38937,
 39106,
 39167,
 39225,
 39271,
 39285,
 39325,
 39652,
 39763,
 39941,
 39960,
 39967,
 39968,
 40164,
 40257,
 40260,
 40271,
 40349,
 40361,
 40500,
 40780,
 40861,
 40886,
 40904,
 40948,
 40968,
 41013,
 41091,
 41209,
 41667,
 41697,
 41789,
 41911,
 41940,
 41980,
 42002,
 42346,
 42388,
 42390,
 42466,
 42641,
 43001,
 43132,
 43359,
 43437,
 43439,
 43530,
 43552,
 43690,
 43718,
 43787,
 43818,
 43998,
 44043,
 44089,
 44162,
 44333,
 44398,
 44454,
 44539,
 44558,
 44705,
 44719,
 44746,
 44959,
 44977,
 44998,
 45260,
 45277,
 45348,
 45360,
 45395,
 45695,
 46647,
 46887,
 47159,
 47251,
 47588,
 47689,
 47740,
 47741,
 47852,
 47992,
 48005,
 48041,
 48086,
 48239,
 48412,
 48637,
 48734,
 48735,
 48766,
 48770,
 49207,
 49245,
 49252,
 49383,
 49728,
 49897,
 49946,
 49949,
 50165,
 50169,
 50184,
 50273,
 50320,
 50324,
 50484,
 50643,
 50675,
 50678,
 51232,
 51248,
 51272,
 51312,
 51370,
 51422,
 51471,
 51494,
 51507,
 51531,
 51599,
 51643,
 51768,
 51838,
 52072,
 52210,
 52245,
 52276,
 52278,
 52299,
 52309,
 52310,
 52319,
 52322,
 52323,
 52324,
 52333,
 52355,
 52357,
 52358,
 52388,
 52412,
 52447,
 52524,
 52705,
 52844,
 52915,
 52923,
 53004,
 53170,
 53300,
 53420,
 53442,
 53473,
 53552,
 53571,
 53604,
 53624,
 53630,
 53693,
 53696,
 53725,
 53739,
 53759,
 53793,
 54035,
 54056,
 54114,
 54126,
 54140,
 54189,
 54276,
 54287,
 54307,
 54309,
 54322,
 54557,
 54649,
 54677,
 54716,
 54720,
 54809,
 54929,
 54991,
 55044,
 55116,
 55581,
 55642,
 55927,
 55933,
 56059,
 56088,
 56160,
 56200,
 56206,
 56218,
 56477,
 56562,
 56565,
 56603,
 56723,
 56902,
 57117,
 57175,
 57185,
 57270,
 57282,
 57333,
 57508,
 57565,
 57736,
 58035,
 58242,
 58276,
 58334,
 58400,
 58473,
 58493,
 58497,
 58534,
 58582,
 58592,
 58788,
 59051,
 59210,
 59273,
 59657,
 59973,
 60015,
 60078,
 60145,
 60630,
 60634,
 60635,
 60724,
 60912,
 60949,
 60952,
 61260,
 61336,
 61429,
 61759,
 61768,
 61934,
 61938,
 61948,
 61970,
 62189,
 62646,
 62680,
 62817,
 62915,
 62916,
 62917,
 62918,
 62922,
 62931,
 62943,
 62958,
 62968,
 62971,
 63210,
 63286,
 63336,
 63357,
 63394,
 63418,
 63720,
 63792,
 63827,
 63845,
 63973,
 64055,
 64105,
 64121,
 64219,
 64266,
 64403,
 64464,
 64514,
 64601,
 64619,
 64845,
 64936,
 64944,
 65040,
 65107,
 65175,
 65200,
 65233,
 65248,
 65273,
 65279,
 65332,
 65412,
 65594,
 65596,
 65608,
 65671,
 65827,
 65869,
 66053,
 66271,
 66275,
 66292,
 66329,
 66372,
 66475,
 66477,
 66666,
 66760,
 66815,
 66821,
 66896,
 67049,
 67081,
 67115,
 67351,
 67681,
 67699,
 68008,
 68198,
 68215,
 68262,
 68374,
 68499,
 68561,
 68631,
 68729,
 68772,
 68788,
 68793,
 68950,
 69144,
 69313,
 69363,
 69414,
 69423,
 69470,
 69499,
 69594,
 69598,
 69605,
 69682,
 69873,
 69922,
 70096,
 70127,
 70215,
 70312,
 70324,
 70327,
 70510,
 70511,
 70701,
 70732,
 71096,
 71149,
 71160,
 71168,
 71183,
 71185,
 71211,
 71217,
 71224,
 71245,
 71264,
 71344,
 71380,
 71480,
 71553,
 71615,
 71848,
 71849,
 72221,
 72329,
 72335,
 72404,
 72914,
 72958,
 73293,
 73303,
 73316,
 73337,
 73356,
 73482,
 73697,
 73871,
 74007,
 74009,
 74060,
 74065,
 74086,
 74175,
 74513,
 74537,
 74577,
 74586,
 74856,
 74873,
 74914,
 74936,
 75001,
 75402,
 75413,
 75426,
 75440,
 75714,
 75834,
 76306,
 76345,
 76415,
 76417,
 76735,
 76763,
 76952,
 76954,
 76967,
 77072,
 77113,
 77226,
 77249,
 77622,
 77766,
 77911,
 78357,
 78498,
 78551,
 78720,
 79538,
 79664,
 80199,
 80206,
 80208,
 80235,
 80275,
 80298,
 80754,
 81034,
 81044,
 81081,
 81086,
 81124,
 81146,
 81163,
 81168,
 81248,
 81254,
 81257,
 81286,
 81391,
 81452,
 81500,
 81520,
 81529,
 81541,
 81751,
 81758,
 81774,
 81828,
 82064,
 82152,
 82299,
 82363,
 82389,
 82413,
 82417,
 82619,
 82694,
 82750,
 82910,
 83070,
 83077,
 83137,
 83656,
 83743,
 83758,
 83936,
 84297,
 84436,
 84458,
 84472,
 84478,
 84574,
 84666,
 84687,
 84702,
 84703,
 84704,
 84707,
 84709,
 84710,
 84711,
 84712,
 84717,
 84718,
 84723,
 84725,
 84726,
 84731,
 84733,
 84734,
 84737,
 84741,
 84742,
 84743,
 84744,
 84745,
 84750,
 84755,
 84756,
 84758,
 84759,
 84760,
 84761,
 84763,
 84764,
 84766,
 84767,
 84768,
 84770,
 84771,
 84772,
 84773,
 84774,
 84775,
 84776,
 84777,
 84778,
 84779,
 84780,
 84781,
 84782,
 84783,
 84785,
 84786,
 84789,
 84792,
 84793,
 84795,
 84797,
 84801,
 84802,
 84803,
 84804,
 84805,
 84806,
 84809,
 84810,
 84818,
 84821,
 84822,
 84823,
 84826,
 84827,
 84831,
 84833,
 84842,
 84843,
 84844,
 84845,
 84846,
 84847,
 84848,
 84853,
 84854,
 84855,
 84858,
 84859,
 84862,
 84863,
 84864,
 84865,
 84866,
 84867,
 84868,
 84869,
 84870,
 84871,
 84874,
 84876,
 84881,
 84882,
 84884,
 84885,
 84886,
 84887,
 84888,
 84889,
 84892,
 84893,
 84894,
 84895,
 84897,
 84898,
 84899,
 84900,
 84901,
 84903,
 84904,
 84905,
 84906,
 84908,
 84909,
 84910,
 84911,
 84913,
 84914,
 84915,
 84917,
 84918,
 84921,
 84923,
 84924,
 84925,
 84927,
 84928,
 84929,
 84930,
 84931,
 84933,
 84934,
 84935,
 84939,
 84940,
 84942,
 84943,
 84944,
 84945,
 84946,
 84947,
 84948,
 84949,
 84950,
 84951,
 84952,
 84953,
 84954,
 84955,
 84956,
 84957,
 84958,
 84959,
 84961,
 84962,
 84963,
 84964,
 84965,
 84966,
 ...]

In [60]:
len(dict_3categ_tweet_ind["mp_merch"])

6875

In [65]:
df_bank_merch = df_unique.iloc[dict_3categ_tweet_ind["bank_merch"],:]

In [76]:
df_bank_merch["text"].iloc[50]

'applepay tipped to arrive in the uk on july 14 according to leaked waitrose ... - digital spy uk'

In [ ]:
def is_entity_present(sent, entity):
    sent = sent.translate(None, string.punctuation)
    ent_item_as_separate_word = False
    # if it appears as separate words inside the text
    if (" " + entity + " ") in sent:
        return True
    # if it appears as separate words at first
    ind_first_match = sent.find(entity+" ")
    if ind_first_match == 0:
        return True
    # if it appears as separate words at the end
    ind_last_match = sent.rfind(" "+entity)
    if ind_last_match + len(entity) + 1 == len(sent):
        return True
    return False

In [82]:
for ind, row in df_unique.iterrows():#df_sample.iterrows():#
    if ind == 103:
        text = row["text"]
        has_bank, has_merch, has_mp = False,False,False
        for tmp,b in df_banks.iterrows():
            if is_entity_present(text, b["Bank"]):
                print b["Bank"]
                has_bank = True
                break
        for tmp, merch in df_merchants.iterrows():
            if is_entity_present(text, merch["Merchant"]):
                print merch["Merchant"]
                has_merch = True
                break
        for tmp, mp in df_mobile_payments.iterrows():
            if is_entity_present(text, mp["mp"]):
                print mp["mp"]
                has_mp = True
                break
        print has_bank, has_merch, has_mp
        break

ing
business
googlewallet
True True True

In [87]:
for a,b in df_banks.iterrows():
    if "ing" in b["Bank"]:
        print b["Bank"]

ingenico
ingnl
ing